name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore TheBackend.sln
      - name: Format
        run: dotnet format TheBackend.sln --no-restore
      - name: Build
        run: dotnet build TheBackend.sln -c Release --no-restore
      - name: Test
        run: dotnet test TheBackend.sln --no-build --verbosity normal
